const ts = (dateString) => ({
  seconds: Math.floor(new Date(dateString).getTime() / 1000),
  nanoseconds: 0,
});

export const ARBOLES_MAPEADOS_MOCK = [
  {
    id: "mock-arbol-ceibo-2025",
    latitud: -17.3917,
    longitud: -66.1448,
    lugarDePlantacion: "Parque",
    mapeadoPor: "12YxHGKBo9YCqCryrGIdDQOpvcM2",
    monitoreos: {
      mon1: {
        altura: 4.2,
        diametroAlturaPecho: 18.5,
        fotoArbolCompleto: "",
        monitoreoRealizadoPor: "12YxHGKBo9YCqCryrGIdDQOpvcM2",
        timestamp: ts("2025-03-15T10:30:00-04:00"),
      },
    },
    nombreCientifico: "Schinus molle",
    nombreComun: "Molle",
    nombrePropio: "Ceibo Norte",
    proyecto: "Arbu",
  },
  {
    id: "mock-arbol-panda-2025",
    latitud: -17.395,
    longitud: -66.15,
    lugarDePlantacion: "Acera o Calle",
    mapeadoPor: "28u6DxbqyPciOwxPZz0ff0zpFKE3",
    monitoreos: {
      mon1: {
        altura: 6.1,
        diametroAlturaPecho: 32.4,
        fotoArbolCompleto: "",
        monitoreoRealizadoPor: "28u6DxbqyPciOwxPZz0ff0zpFKE3",
        timestamp: ts("2025-05-20T16:45:00-04:00"),
      },
    },
    nombreCientifico: "Tipuana tipu",
    nombreComun: "Tipa",
    nombrePropio: "Panda Centro",
    proyecto: "Arbu",
  },
  {
    id: "mock-arbol-incas-2025",
    latitud: -17.388,
    longitud: -66.138,
    lugarDePlantacion: "Jardín",
    mapeadoPor: "2JPihJj1DdXrvVxSupsKPxgK1ZV2",
    monitoreos: {
      mon1: {
        altura: 3.8,
        diametroAlturaPecho: 15.2,
        fotoArbolCompleto: "",
        monitoreoRealizadoPor: "2JPihJj1DdXrvVxSupsKPxgK1ZV2",
        timestamp: ts("2025-07-08T09:15:00-04:00"),
      },
    },
    nombreCientifico: "Jacaranda mimosifolia",
    nombreComun: "Tarco",
    nombrePropio: "Incas Sur",
    proyecto: "Arbu",
  },
  {
    id: "mock-arbol-mafeking-2025",
    latitud: -17.4,
    longitud: -66.16,
    lugarDePlantacion: "Plaza",
    mapeadoPor: "3QasLpP5fUOMScdVD8IYuNNvNg63",
    monitoreos: {
      mon1: {
        altura: 5.6,
        diametroAlturaPecho: 29.36,
        fotoArbolCompleto: "",
        monitoreoRealizadoPor: "3QasLpP5fUOMScdVD8IYuNNvNg63",
        timestamp: ts("2025-10-11T21:22:22-04:00"),
      },
    },
    nombreCientifico: "Schinus molle",
    nombreComun: "Molle",
    nombrePropio: "Mafeking Este",
    proyecto: "Arbu",
  },
  {
    id: "mock-arbol-bolivia-2025",
    latitud: -17.385,
    longitud: -66.155,
    lugarDePlantacion: "Acera o Calle",
    mapeadoPor: "o7i3yjuvqJfMu7GgjRSCv9YWLeA2",
    monitoreos: {
      mon1: {
        altura: 2.9,
        diametroAlturaPecho: 12.8,
        fotoArbolCompleto: "",
        monitoreoRealizadoPor: "o7i3yjuvqJfMu7GgjRSCv9YWLeA2",
        timestamp: ts("2025-11-02T14:00:00-04:00"),
      },
    },
    nombreCientifico: "Platanus acerifolia",
    nombreComun: "Plátano",
    nombrePropio: "",
    proyecto: "Arbu",
  },
  {
    id: "mock-arbol-aleman-2025-a",
    latitud: -17.3925,
    longitud: -66.148,
    lugarDePlantacion: "Parque",
    mapeadoPor: "NRvx0BKZFSMobQGMhuLdLq3Hcj52",
    monitoreos: {
      mon1: {
        altura: 4.5,
        diametroAlturaPecho: 20.1,
        fotoArbolCompleto: "",
        monitoreoRealizadoPor: "NRvx0BKZFSMobQGMhuLdLq3Hcj52",
        timestamp: ts("2025-04-10T11:00:00-04:00"),
      },
    },
    nombreCientifico: "Celtis iguanaea",
    nombreComun: "Algarrobo",
    nombrePropio: "Alemán A",
    proyecto: "Arbu",
  },
  {
    id: "mock-arbol-aleman-2025-b",
    latitud: -17.394,
    longitud: -66.142,
    lugarDePlantacion: "Jardín",
    mapeadoPor: "0aOsmmbD3rgWcouMfEj5UWibWko1",
    monitoreos: {
      mon1: {
        altura: 3.2,
        diametroAlturaPecho: 14.6,
        fotoArbolCompleto: "",
        monitoreoRealizadoPor: "0aOsmmbD3rgWcouMfEj5UWibWko1",
        timestamp: ts("2025-06-22T08:30:00-04:00"),
      },
    },
    nombreCientifico: "Morus alba",
    nombreComun: "Mora",
    nombrePropio: "Alemán B",
    proyecto: "Arbu",
  },
  {
    id: "mock-arbol-aleman-2025-c",
    latitud: -17.397,
    longitud: -66.146,
    lugarDePlantacion: "Plaza",
    mapeadoPor: "0jR2YhfJj7a2TGSG0uFB9zkGmK03",
    monitoreos: {
      mon1: {
        altura: 7.3,
        diametroAlturaPecho: 35.9,
        fotoArbolCompleto: "",
        monitoreoRealizadoPor: "0jR2YhfJj7a2TGSG0uFB9zkGmK03",
        timestamp: ts("2025-09-18T17:20:00-04:00"),
      },
    },
    nombreCientifico: "Eucalyptus globulus",
    nombreComun: "Eucalipto",
    nombrePropio: "Alemán C",
    proyecto: "Arbu",
  },
  {
    id: "mock-arbol-sin-inscripcion-2025",
    latitud: -17.389,
    longitud: -66.152,
    lugarDePlantacion: "Acera o Calle",
    mapeadoPor: "usuario-sin-inscripcion",
    monitoreos: {
      mon1: {
        altura: 4.0,
        diametroAlturaPecho: 17.0,
        fotoArbolCompleto: "",
        monitoreoRealizadoPor: "usuario-sin-inscripcion",
        timestamp: ts("2025-08-01T12:00:00-04:00"),
      },
    },
    nombreCientifico: "Acacia dealbata",
    nombreComun: "Aromo",
    nombrePropio: "Sin inscripción",
    proyecto: "Arbu",
  },
  {
    id: "mock-arbol-ceibo-2024",
    latitud: -17.386,
    longitud: -66.14,
    lugarDePlantacion: "Parque",
    mapeadoPor: "12YxHGKBo9YCqCryrGIdDQOpvcM2",
    monitoreos: {
      mon1: {
        altura: 5.0,
        diametroAlturaPecho: 22.0,
        fotoArbolCompleto: "",
        monitoreoRealizadoPor: "12YxHGKBo9YCqCryrGIdDQOpvcM2",
        timestamp: ts("2024-11-15T10:00:00-04:00"),
      },
    },
    nombreCientifico: "Schinus molle",
    nombreComun: "Molle",
    nombrePropio: "Ceibo 2024",
    proyecto: "Arbu",
  },
];
