export const INSCRIPCIONES_MAPEO_MOCK = [
  {
    id: "NRvx0BKZFSMobQGMhuLdLq3Hcj52",
    email: "alisoncallizaya9@gmail.com",
    estado: "Aceptado",
    grupo: "Alemán",
    nombre: "Erick Gomez",
    pagado: false,
    rama: "Lobatos",
  },
  {
    id: "0aOsmmbD3rgWcouMfEj5UWibWko1",
    email: "alisoncallizaya9@gmail.com",
    estado: "Aceptado",
    grupo: "Alemán",
    nombre: "Alison Callizaya",
    pagado: false,
    rama: "Lobatos",
  },
  {
    id: "0jR2YhfJj7a2TGSG0uFB9zkGmK03",
    email: "alejandraseed@gmail.com",
    estado: "Aceptado",
    grupo: "Alemán",
    nombre: "ALEK GRUEL",
    pagado: true,
    rama: "Exploradores",
  },
  {
    id: "12YxHGKBo9YCqCryrGIdDQOpvcM2",
    email: "carlosyqsy@gmail.com",
    estado: "Aceptado",
    grupo: "Ceibo",
    nombre: "Carlos Javier",
    pagado: false,
    rama: "Rovers",
  },
  {
    id: "28u6DxbqyPciOwxPZz0ff0zpFKE3",
    email: "aleyda.kattya.mc@gmail.com",
    estado: "Aceptado",
    grupo: "Panda",
    nombre: "Aleyda Kattya Mamani Cortez",
    pagado: true,
    rama: "Pioneros",
  },
  {
    id: "2JPihJj1DdXrvVxSupsKPxgK1ZV2",
    email: "damariszapana56@gmail.com",
    estado: "Aceptado",
    grupo: "Incas",
    nombre: "Damaris Zapana",
    pagado: false,
    rama: "Pioneros",
  },
  {
    id: "3QasLpP5fUOMScdVD8IYuNNvNg63",
    email: "miaugatos833@gmail.com",
    estado: "Aceptado",
    grupo: "Mafeking",
    nombre: "Diana Alison Ramos Moya",
    pagado: false,
    rama: "Pioneros",
  },
  {
    id: "o7i3yjuvqJfMu7GgjRSCv9YWLeA2",
    email: "javiermancilla123451@gmail.com",
    estado: "Aceptado",
    grupo: "Bolivia",
    nombre: "Alison Ramos",
    pagado: false,
    rama: "Lobatos",
  },
];
