export const types = {
  setUser:'[LOGIN] Set user',
  clearUser:'[LOGIN] Clear user',
  mapaActiveArbol:'[MAPA] Set active arbol',
  mapaLoadArboles:'[MAPA] Load arboles',
  mapaLoadArbolesMapeados:'[MAPA] Load arboles mapeados',
  dashboardLoadInscripciones:'[DASHBOARD] Load inscripciones',
  dashboardUpdateInscripcion:'[DASHBOARD] Update inscripcion',
  dashboardDeleteInscripcion:'[DASHBOARD] Delete inscripcion',
  tablaUpdateNombreMapeado:'[TABLA] Update nombre mapeado',
  mapaHideDetailArbol: '[MAPA] Hide detail arbol',
  mapaLoadUsuarios:'[MAPA] Load usuarios',
  mapaSetActiveMonitoreo:'[MAPA] Set active monitoreo',
  mapaFilterArboles:'[MAPA] Filter arboles',
  mapaIsFiltered:'[MAPA] Se aplico filtro',
  catalogoLoadEspecies:'[CATALOGO] Load catalogo',
  catalogoSetActiveEspecie:'[CATALOGO] Set active especie',
  catalogoHideDetailEspecie: '[CATALOGO] Hide detail especie',
  leaderboardLoadScoresMes: '[LEADERBOARD] Load scores del Mes',
  leaderboardLoadScoresGlobal: '[LEADERBOARD] Load scores Global',
}