export const types = {
  mapaActiveArbol: '[MAPA] Set active arbol',
  mapaArbolSeleccionado: '[MAPA] Set arbol selected',
  mapaShowArbolesPlantados: '[MAPA] Show data arboles plantados',
  mapaShowArbolesMapeados: '[MAPA] Show data arboles mapeados',
  mapaFiltrarArboles: '[MAPA] Filtrar arboles',
  mapaBorrarFiltros: '[MAPA] Borrar filtro',
  mapaBusquedaArbol: '[MAPA] Buscar arboles',
  mapaLoadArboles: '[MAPA] Load arboles',
  mapaHideDetailArbol: '[MAPA] Hide detail arbol',
  mapaLoadUsuarios: '[MAPA] Load usuarios',
  mapaSetActiveMonitoreo: '[MAPA] Set active monitoreo',
  mapaFilterArboles: '[MAPA] Filter arboles',
  mapaIsFiltered: '[MAPA] Se aplico filtro',
  catalogoLoadEspecies: '[CATALOGO] Load catalogo',
  catalogoSetActiveEspecie: '[CATALOGO] Set active especie',
  catalogoHideDetailEspecie: '[CATALOGO] Hide detail especie',
  leaderboardLoadScoresMes: '[LEADERBOARD] Load scores del Mes',
  leaderboardLoadScoresGlobal: '[LEADERBOARD] Load scores Global',
}
