export const sugerenciasNombresCientificos = [
  "Abutilon megapotamicum",
  "Acacia melanoxylon",
  "Acalypha fulva",
  "Acer negundo L.",
  "Aloysia critrodora Palau",
  "Aspidosperma horko-kebracho",
  "Baccharis dracunculifolia",
  "Baccharis salicifolia",
  "Bahuinia forticata Link.",
  "Brachychiton populneus",
  "Brunfelsia australis Benth.",
  "Caesalpinia pulcherrimia",
  "Calliandra parvifolia (Hook. & Arn.) Speg.",
  "Callistemon citrinus (Curtis) Skeels.",
  "Callistemon viminalis",
  "Cantua bicolor",
  "Casuarina equisetifolia",
  "Cedrela lilloi C. DC. (Cedrela angustifolia Sessé & Moc. ex DC.).",
  "Ceiba boliviana",
  "Citrus x limon",
  "Citrus x paradisi",
  "Cojoba arborea (L.) Britton & Rose",
  "Cupressus macrocarpa",
  "Cupressus sempervirens L.",
  "Delonix regia",
  "Dodonaea viscosa Jacq.",
  "Enterolobium contortisiliquum (Vell.) Morong",
  "Eriobotrya japónica (Thunb) Lindl.",
  "Erythrina falcata Benth.",
  "Eucaliptus globulus",
  "Euphorbia cotinifolia",
  "Euphorbia pulcherrima",
  "Ficus benjamina",
  "Ficus elastica",
  "Fraxinus americana",
  "Grevillea robusta",
  "Handroanthus (Tabebuia) impetiginosus (Mart. ex DC.) Mattos.",
  "Handroanthus serratifolius",
  "Hibiscus rosa-sinensis L.",
  "Hibiscus schizopetalus",
  "Hibiscus syriacus",
  "Inga edulis (ynga) (Vell.) J.W. Moore.",
  "Inga feuillei",
  "Jacarandá mimosifolia D. Don",
  "Kageneckia lanceolata Ruiz & Pav.",
  "Lagerstroemia indica L.",
  "Lavanda angustifolia",
  "Leucaena leucocephala",
  "Ligustrum lucidum",
  "Magnolia grandiflora L.",
  "Melia Azederach",
  "Nerium oleander L.",
  "Nicotiana glauca",
  "Olea europea",
  "Parkinsonia aculeata L.",
  "Phanera variegata L. Benth.",
  "Phytolacca dioica",
  "Pinus radiata",
  "Populus deltoides",
  "Populus nigra",
  "Prosopis alba Griseb.",
  "Psidium guajava",
  "Punica granatum",
  "Salix babilonica",
  "Salix humboldtiana",
  "Salvia rosmarinus",
  "Sambucus peruviana",
  "Schefflera arboricola",
  "Schinopsis haenkeana Engl.",
  "Schinus fasciculata",
  "Schinus molle",
  "Schinus pearcei Engl.",
  "Senegalia (Acacia) visco (Lorentz ex Griseb.) Seigler & Ebinger",
  "Senna aymara HS Irwin & Barneby",
  "Senna didymobotrya",
  "Senna spectabilis (DC.) H.S. Irwin & Barneby.",
  "Spathodea campanulata",
  "Streptosolen jamesonii",
  "Tara spinosa (Feuillée ex Molina) Britton & Rose",
  "Tecoma fulva subsp. garrocha (Hieron.) J.R.I. Wood",
  "Tecoma stans var sambucifolia",
  "Tecoma stans var. stans",
  "Thevetia peruviana",
  "Tipuana tipu (Benth.) Kuntze.",
  "Trachelospermum jasminoides",
  "Vachellia aroma",
  "Vachellia caven",
  "Vasconcellea quercifolia",
  "Zanthoxylum coco",
];

export const sugerenciasNombresComunes = [
  "Farolito chino",
  "Acacia negra",
  "Salancachi",
  "Negundo",
  "Cedrón",
  "Kacha kacha",
  "Thola",
  "Thola",
  "Pata de buey",
  "Brachichito",
  "Jazmín paraguayo",
  "Clavelina",
  "Caliandra",
  "Cepillo",
  "Callistemo llorón",
  "Cantuta",
  "Pino australiano",
  "Cedro",
  "Toborochi",
  "Limon",
  "Pomelo",
  "Siraricito",
  "Ciprés",
  "Pino vela",
  "Pajarilla",
  "Chacatea",
  "Oreja de mono",
  "Nispero",
  "Chillijchi",
  "Eucalipto",
  "Camotillo",
  "Flor de navidad",
  "Ficus",
  "Gomero",
  "Fresno blanco",
  "Grevillea",
  "Tajibo rosado",
  "Tajibo amarillo",
  "Cucarda",
  "Hibisco coral",
  "Rosa de siria",
  "Pacay criollo",
  "Pacay",
  "Jacarandá",
  "Lloque",
  "Flor de júpiter",
  "Lavanda",
  "Chamba",
  "Ligustro",
  "Magnolia",
  "Paraíso",
  "Falso laurel",
  "Q'aralawa",
  "Olivo",
  "Sina sina",
  "Pata de buey",
  "Ombú",
  "Pino radiata",
  "Alamo negro",
  "Alamo blanco",
  "Algarrobo",
  "Guayaba",
  "Granada",
  "Sauce llorón",
  "Sauce criollo",
  "Romero",
  "Sauco",
  "Chefflera",
  "Soto",
  "Luyo luyo",
  "Molle",
  "Terebinto",
  "Jarca",
  "Moto moto",
  "Carnavalito",
  "Llamarada de fuego",
  "Trompetita",
  "Tara",
  "Garrocha",
  "LLuvia de oro",
  "Leche leche",
  "Tipa",
  "Jazmin estrella",
  "Kiñi",
  "Churqui",
  "Orq'o karalawa",
  "Chirimolle",
];
